name: Tests
on: push
jobs:
  tests-0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: cd ./0 && npm install
    - name: Run tests
      run: cd ./0 && npm run test