name: Tests
on: push
jobs:
  tests-0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls
    - name: Changing directory
      run: cd ./0
    - name: ls
      run: ls
    - name: Install modules
      run: npm install
    - name: Run tests
      run: cd ./0 && npm run test